/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'contactType' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'gstin' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({
  'trade' : IDL.Null,
  'agreement' : IDL.Null,
  'export' : IDL.Null,
});
export const DocumentRecord = IDL.Record({
  'id' : IDL.Text,
  'categoryText' : IDL.Text,
  'templateId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'fieldValues' : IDL.Text,
  'templateName' : IDL.Text,
  'category' : Category,
});
export const GovernmentScheme = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'documentChecklist' : IDL.Vec(IDL.Text),
  'benefits' : IDL.Text,
  'eligibilityCriteria' : IDL.Text,
  'applicationLink' : IDL.Text,
  'ministryName' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'deliveryDate' : IDL.Int,
  'orderDate' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'contactId' : IDL.Text,
  'items' : IDL.Text,
  'orderNumber' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'mode' : IDL.Text,
  'dueDate' : IDL.Int,
  'orderId' : IDL.Text,
  'paidDate' : IDL.Int,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Shipment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'trackingNumber' : IDL.Text,
  'destination' : IDL.Text,
  'userId' : IDL.Principal,
  'origin' : IDL.Text,
  'dispatchDate' : IDL.Int,
  'deliveryDate' : IDL.Int,
  'orderId' : IDL.Text,
  'carrier' : IDL.Text,
});
export const DocumentTemplate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'fields' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : Category,
});
export const BusinessProfile = IDL.Record({
  'pan' : IDL.Text,
  'ifscCode' : IDL.Text,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'logoAssetId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'email' : IDL.Text,
  'bankName' : IDL.Text,
  'signatoryDesignation' : IDL.Text,
  'authorizedSignatory' : IDL.Text,
  'updatedAt' : IDL.Int,
  'signatureAssetId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'iecCode' : IDL.Text,
  'accountNumber' : IDL.Text,
  'branchName' : IDL.Text,
  'phone' : IDL.Text,
  'profileComplete' : IDL.Bool,
  'udyamNumber' : IDL.Text,
});
export const UsageStats = IDL.Record({
  'documentsPerDay' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Nat)),
  'totalActiveUsers' : IDL.Nat,
  'topTemplates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const UserProfileSummary = IDL.Record({
  'principal' : IDL.Principal,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'profileComplete' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkSchemeEligibility' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'createContact' : IDL.Func([Contact], [], []),
  'createDocumentRecord' : IDL.Func([DocumentRecord], [], []),
  'createGovernmentScheme' : IDL.Func([GovernmentScheme], [], []),
  'createOrder' : IDL.Func([Order], [], []),
  'createPayment' : IDL.Func([Payment], [], []),
  'createShipment' : IDL.Func([Shipment], [], []),
  'createTemplate' : IDL.Func([DocumentTemplate], [], []),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'deleteGovernmentScheme' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'deletePayment' : IDL.Func([IDL.Text], [], []),
  'deleteShipment' : IDL.Func([IDL.Text], [], []),
  'deleteTemplate' : IDL.Func([IDL.Text], [], []),
  'getAllSchemes' : IDL.Func([], [IDL.Vec(GovernmentScheme)], ['query']),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(DocumentTemplate)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getDocumentRecords' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'getGovernmentScheme' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GovernmentScheme)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getShipment' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
  'getShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [IDL.Opt(DocumentTemplate)], ['query']),
  'getUsageStats' : IDL.Func([], [UsageStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfileSummary)], ['query']),
  'saveCallerUserProfile' : IDL.Func([BusinessProfile], [], []),
  'updateContact' : IDL.Func([IDL.Text, Contact], [], []),
  'updateGovernmentScheme' : IDL.Func([IDL.Text, GovernmentScheme], [], []),
  'updateOrder' : IDL.Func([IDL.Text, Order], [], []),
  'updatePayment' : IDL.Func([IDL.Text, Payment], [], []),
  'updateShipment' : IDL.Func([IDL.Text, Shipment], [], []),
  'updateTemplate' : IDL.Func([IDL.Text, DocumentTemplate], [], []),
  'upsertProfile' : IDL.Func([BusinessProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'contactType' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'gstin' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({
    'trade' : IDL.Null,
    'agreement' : IDL.Null,
    'export' : IDL.Null,
  });
  const DocumentRecord = IDL.Record({
    'id' : IDL.Text,
    'categoryText' : IDL.Text,
    'templateId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'fieldValues' : IDL.Text,
    'templateName' : IDL.Text,
    'category' : Category,
  });
  const GovernmentScheme = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'documentChecklist' : IDL.Vec(IDL.Text),
    'benefits' : IDL.Text,
    'eligibilityCriteria' : IDL.Text,
    'applicationLink' : IDL.Text,
    'ministryName' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'deliveryDate' : IDL.Int,
    'orderDate' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'contactId' : IDL.Text,
    'items' : IDL.Text,
    'orderNumber' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'mode' : IDL.Text,
    'dueDate' : IDL.Int,
    'orderId' : IDL.Text,
    'paidDate' : IDL.Int,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Shipment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'destination' : IDL.Text,
    'userId' : IDL.Principal,
    'origin' : IDL.Text,
    'dispatchDate' : IDL.Int,
    'deliveryDate' : IDL.Int,
    'orderId' : IDL.Text,
    'carrier' : IDL.Text,
  });
  const DocumentTemplate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'fields' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : Category,
  });
  const BusinessProfile = IDL.Record({
    'pan' : IDL.Text,
    'ifscCode' : IDL.Text,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'logoAssetId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'email' : IDL.Text,
    'bankName' : IDL.Text,
    'signatoryDesignation' : IDL.Text,
    'authorizedSignatory' : IDL.Text,
    'updatedAt' : IDL.Int,
    'signatureAssetId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'iecCode' : IDL.Text,
    'accountNumber' : IDL.Text,
    'branchName' : IDL.Text,
    'phone' : IDL.Text,
    'profileComplete' : IDL.Bool,
    'udyamNumber' : IDL.Text,
  });
  const UsageStats = IDL.Record({
    'documentsPerDay' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Nat)),
    'totalActiveUsers' : IDL.Nat,
    'topTemplates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const UserProfileSummary = IDL.Record({
    'principal' : IDL.Principal,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'profileComplete' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkSchemeEligibility' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'createContact' : IDL.Func([Contact], [], []),
    'createDocumentRecord' : IDL.Func([DocumentRecord], [], []),
    'createGovernmentScheme' : IDL.Func([GovernmentScheme], [], []),
    'createOrder' : IDL.Func([Order], [], []),
    'createPayment' : IDL.Func([Payment], [], []),
    'createShipment' : IDL.Func([Shipment], [], []),
    'createTemplate' : IDL.Func([DocumentTemplate], [], []),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'deleteGovernmentScheme' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'deletePayment' : IDL.Func([IDL.Text], [], []),
    'deleteShipment' : IDL.Func([IDL.Text], [], []),
    'deleteTemplate' : IDL.Func([IDL.Text], [], []),
    'getAllSchemes' : IDL.Func([], [IDL.Vec(GovernmentScheme)], ['query']),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(DocumentTemplate)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getDocumentRecords' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'getGovernmentScheme' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GovernmentScheme)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getShipment' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
    'getShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DocumentTemplate)],
        ['query'],
      ),
    'getUsageStats' : IDL.Func([], [UsageStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfileSummary)], ['query']),
    'saveCallerUserProfile' : IDL.Func([BusinessProfile], [], []),
    'updateContact' : IDL.Func([IDL.Text, Contact], [], []),
    'updateGovernmentScheme' : IDL.Func([IDL.Text, GovernmentScheme], [], []),
    'updateOrder' : IDL.Func([IDL.Text, Order], [], []),
    'updatePayment' : IDL.Func([IDL.Text, Payment], [], []),
    'updateShipment' : IDL.Func([IDL.Text, Shipment], [], []),
    'updateTemplate' : IDL.Func([IDL.Text, DocumentTemplate], [], []),
    'upsertProfile' : IDL.Func([BusinessProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };