/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'pan' : string,
  'ifscCode' : string,
  'createdAt' : bigint,
  'businessName' : string,
  'logoAssetId' : [] | [Uint8Array],
  'email' : string,
  'bankName' : string,
  'signatoryDesignation' : string,
  'authorizedSignatory' : string,
  'updatedAt' : bigint,
  'signatureAssetId' : [] | [Uint8Array],
  'gstin' : string,
  'address' : string,
  'iecCode' : string,
  'accountNumber' : string,
  'branchName' : string,
  'phone' : string,
  'profileComplete' : boolean,
  'udyamNumber' : string,
}
export type Category = { 'trade' : null } |
  { 'agreement' : null } |
  { 'export' : null };
export interface Contact {
  'id' : string,
  'contactType' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'company' : string,
  'gstin' : string,
  'notes' : string,
  'category' : string,
  'phone' : string,
}
export interface DocumentRecord {
  'id' : string,
  'categoryText' : string,
  'templateId' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'fieldValues' : string,
  'templateName' : string,
  'category' : Category,
}
export interface DocumentTemplate {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'fields' : string,
  'updatedAt' : bigint,
  'category' : Category,
}
export interface GovernmentScheme {
  'id' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'documentChecklist' : Array<string>,
  'benefits' : string,
  'eligibilityCriteria' : string,
  'applicationLink' : string,
  'ministryName' : string,
}
export interface Order {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'deliveryDate' : bigint,
  'orderDate' : bigint,
  'totalAmount' : number,
  'contactId' : string,
  'items' : string,
  'orderNumber' : string,
}
export interface Payment {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'mode' : string,
  'dueDate' : bigint,
  'orderId' : string,
  'paidDate' : bigint,
  'notes' : string,
  'amount' : number,
}
export interface Shipment {
  'id' : string,
  'status' : string,
  'trackingNumber' : string,
  'destination' : string,
  'userId' : Principal,
  'origin' : string,
  'dispatchDate' : bigint,
  'deliveryDate' : bigint,
  'orderId' : string,
  'carrier' : string,
}
export interface UsageStats {
  'documentsPerDay' : Array<[bigint, bigint]>,
  'totalActiveUsers' : bigint,
  'topTemplates' : Array<[string, bigint]>,
}
export interface UserProfileSummary {
  'principal' : Principal,
  'businessName' : string,
  'email' : string,
  'profileComplete' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkSchemeEligibility' : ActorMethod<[string], Array<string>>,
  'createContact' : ActorMethod<[Contact], undefined>,
  'createDocumentRecord' : ActorMethod<[DocumentRecord], undefined>,
  'createGovernmentScheme' : ActorMethod<[GovernmentScheme], undefined>,
  'createOrder' : ActorMethod<[Order], undefined>,
  'createPayment' : ActorMethod<[Payment], undefined>,
  'createShipment' : ActorMethod<[Shipment], undefined>,
  'createTemplate' : ActorMethod<[DocumentTemplate], undefined>,
  'deleteContact' : ActorMethod<[string], undefined>,
  'deleteGovernmentScheme' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[string], undefined>,
  'deleteShipment' : ActorMethod<[string], undefined>,
  'deleteTemplate' : ActorMethod<[string], undefined>,
  'getAllSchemes' : ActorMethod<[], Array<GovernmentScheme>>,
  'getAllTemplates' : ActorMethod<[], Array<DocumentTemplate>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[string], [] | [Contact]>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getDocumentRecords' : ActorMethod<[bigint, bigint], Array<DocumentRecord>>,
  'getGovernmentScheme' : ActorMethod<[string], [] | [GovernmentScheme]>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPayment' : ActorMethod<[string], [] | [Payment]>,
  'getPayments' : ActorMethod<[], Array<Payment>>,
  'getProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getShipment' : ActorMethod<[string], [] | [Shipment]>,
  'getShipments' : ActorMethod<[], Array<Shipment>>,
  'getTemplate' : ActorMethod<[string], [] | [DocumentTemplate]>,
  'getUsageStats' : ActorMethod<[], UsageStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [BusinessProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfileSummary>>,
  'saveCallerUserProfile' : ActorMethod<[BusinessProfile], undefined>,
  'updateContact' : ActorMethod<[string, Contact], undefined>,
  'updateGovernmentScheme' : ActorMethod<[string, GovernmentScheme], undefined>,
  'updateOrder' : ActorMethod<[string, Order], undefined>,
  'updatePayment' : ActorMethod<[string, Payment], undefined>,
  'updateShipment' : ActorMethod<[string, Shipment], undefined>,
  'updateTemplate' : ActorMethod<[string, DocumentTemplate], undefined>,
  'upsertProfile' : ActorMethod<[BusinessProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];