/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GovernmentScheme {
    id: string;
    name: string;
    description: string;
    isActive: boolean;
    documentChecklist: Array<string>;
    benefits: string;
    eligibilityCriteria: string;
    applicationLink: string;
    ministryName: string;
}
export interface DocumentTemplate {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    fields: string;
    updatedAt: bigint;
    category: Category;
}
export interface DocumentRecord {
    id: string;
    categoryText: string;
    templateId: string;
    userId: Principal;
    createdAt: bigint;
    fieldValues: string;
    templateName: string;
    category: Category;
}
export interface Shipment {
    id: string;
    status: string;
    trackingNumber: string;
    destination: string;
    userId: Principal;
    origin: string;
    dispatchDate: bigint;
    deliveryDate: bigint;
    orderId: string;
    carrier: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Contact {
    id: string;
    contactType: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    email: string;
    company: string;
    gstin: string;
    notes: string;
    category: string;
    phone: string;
}
export interface UserProfileSummary {
    principal: Principal;
    businessName: string;
    email: string;
    profileComplete: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: string;
    status: string;
    userId: Principal;
    mode: string;
    dueDate: bigint;
    orderId: string;
    paidDate: bigint;
    notes: string;
    amount: number;
}
export interface UsageStats {
    documentsPerDay: Array<[bigint, bigint]>;
    totalActiveUsers: bigint;
    topTemplates: Array<[string, bigint]>;
}
export interface Order {
    id: string;
    status: string;
    userId: Principal;
    deliveryDate: bigint;
    orderDate: bigint;
    totalAmount: number;
    contactId: string;
    items: string;
    orderNumber: string;
}
export interface BusinessProfile {
    pan: string;
    ifscCode: string;
    createdAt: bigint;
    businessName: string;
    logoAssetId?: Uint8Array;
    email: string;
    bankName: string;
    signatoryDesignation: string;
    authorizedSignatory: string;
    updatedAt: bigint;
    signatureAssetId?: Uint8Array;
    gstin: string;
    address: string;
    iecCode: string;
    accountNumber: string;
    branchName: string;
    phone: string;
    profileComplete: boolean;
    udyamNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    trade = "trade",
    agreement = "agreement",
    export_ = "export"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkSchemeEligibility(questionnaire: string): Promise<Array<string>>;
    createContact(contact: Contact): Promise<void>;
    createDocumentRecord(record: DocumentRecord): Promise<void>;
    createGovernmentScheme(scheme: GovernmentScheme): Promise<void>;
    createOrder(order: Order): Promise<void>;
    createPayment(payment: Payment): Promise<void>;
    createShipment(shipment: Shipment): Promise<void>;
    createTemplate(template: DocumentTemplate): Promise<void>;
    deleteContact(contactId: string): Promise<void>;
    deleteGovernmentScheme(schemeId: string): Promise<void>;
    deleteOrder(orderId: string): Promise<void>;
    deletePayment(paymentId: string): Promise<void>;
    deleteShipment(shipmentId: string): Promise<void>;
    deleteTemplate(templateId: string): Promise<void>;
    getAllSchemes(): Promise<Array<GovernmentScheme>>;
    getAllTemplates(): Promise<Array<DocumentTemplate>>;
    getCallerUserProfile(): Promise<BusinessProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContact(contactId: string): Promise<Contact | null>;
    getContacts(): Promise<Array<Contact>>;
    getDocumentRecords(page: bigint, pageSize: bigint): Promise<Array<DocumentRecord>>;
    getGovernmentScheme(schemeId: string): Promise<GovernmentScheme | null>;
    getOrder(orderId: string): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getPayment(paymentId: string): Promise<Payment | null>;
    getPayments(): Promise<Array<Payment>>;
    getProfile(): Promise<BusinessProfile | null>;
    getShipment(shipmentId: string): Promise<Shipment | null>;
    getShipments(): Promise<Array<Shipment>>;
    getTemplate(templateId: string): Promise<DocumentTemplate | null>;
    getUsageStats(): Promise<UsageStats>;
    getUserProfile(user: Principal): Promise<BusinessProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllUsers(): Promise<Array<UserProfileSummary>>;
    saveCallerUserProfile(profile: BusinessProfile): Promise<void>;
    updateContact(contactId: string, contact: Contact): Promise<void>;
    updateGovernmentScheme(schemeId: string, scheme: GovernmentScheme): Promise<void>;
    updateOrder(orderId: string, order: Order): Promise<void>;
    updatePayment(paymentId: string, payment: Payment): Promise<void>;
    updateShipment(shipmentId: string, shipment: Shipment): Promise<void>;
    updateTemplate(templateId: string, template: DocumentTemplate): Promise<void>;
    upsertProfile(profile: BusinessProfile): Promise<void>;
}
import type { BusinessProfile as _BusinessProfile, Category as _Category, Contact as _Contact, DocumentRecord as _DocumentRecord, DocumentTemplate as _DocumentTemplate, GovernmentScheme as _GovernmentScheme, Order as _Order, Payment as _Payment, Shipment as _Shipment, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkSchemeEligibility(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSchemeEligibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSchemeEligibility(arg0);
            return result;
        }
    }
    async createContact(arg0: Contact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0);
            return result;
        }
    }
    async createDocumentRecord(arg0: DocumentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocumentRecord(to_candid_DocumentRecord_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocumentRecord(to_candid_DocumentRecord_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createGovernmentScheme(arg0: GovernmentScheme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGovernmentScheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGovernmentScheme(arg0);
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return result;
        }
    }
    async createPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0);
            return result;
        }
    }
    async createShipment(arg0: Shipment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShipment(arg0);
            return result;
        }
    }
    async createTemplate(arg0: DocumentTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemplate(to_candid_DocumentTemplate_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemplate(to_candid_DocumentTemplate_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteContact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteGovernmentScheme(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGovernmentScheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGovernmentScheme(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deletePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteShipment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShipment(arg0);
            return result;
        }
    }
    async deleteTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async getAllSchemes(): Promise<Array<GovernmentScheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSchemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSchemes();
            return result;
        }
    }
    async getAllTemplates(): Promise<Array<DocumentTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTemplates();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTemplates();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: string): Promise<Contact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getDocumentRecords(arg0: bigint, arg1: bigint): Promise<Array<DocumentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentRecords(arg0, arg1);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentRecords(arg0, arg1);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGovernmentScheme(arg0: string): Promise<GovernmentScheme | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGovernmentScheme(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGovernmentScheme(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return result;
        }
    }
    async getPayment(arg0: string): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return result;
        }
    }
    async getProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShipment(arg0: string): Promise<Shipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipment(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipment(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShipments(): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipments();
            return result;
        }
    }
    async getTemplate(arg0: string): Promise<DocumentTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsageStats(): Promise<UsageStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfileSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_BusinessProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_BusinessProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateContact(arg0: string, arg1: Contact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1);
            return result;
        }
    }
    async updateGovernmentScheme(arg0: string, arg1: GovernmentScheme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGovernmentScheme(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGovernmentScheme(arg0, arg1);
            return result;
        }
    }
    async updateOrder(arg0: string, arg1: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, arg1);
            return result;
        }
    }
    async updatePayment(arg0: string, arg1: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1);
            return result;
        }
    }
    async updateShipment(arg0: string, arg1: Shipment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipment(arg0, arg1);
            return result;
        }
    }
    async updateTemplate(arg0: string, arg1: DocumentTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemplate(arg0, to_candid_DocumentTemplate_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemplate(arg0, to_candid_DocumentTemplate_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProfile(to_candid_BusinessProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProfile(to_candid_BusinessProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BusinessProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentRecord_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentRecord): DocumentRecord {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentTemplate_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentTemplate): DocumentTemplate {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contact]): Contact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GovernmentScheme]): GovernmentScheme | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shipment]): Shipment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentTemplate]): DocumentTemplate | null {
    return value.length === 0 ? null : from_candid_DocumentTemplate_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    fields: string;
    updatedAt: bigint;
    category: _Category;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    fields: string;
    updatedAt: bigint;
    category: Category;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        fields: value.fields,
        updatedAt: value.updatedAt,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan: string;
    ifscCode: string;
    createdAt: bigint;
    businessName: string;
    logoAssetId: [] | [Uint8Array];
    email: string;
    bankName: string;
    signatoryDesignation: string;
    authorizedSignatory: string;
    updatedAt: bigint;
    signatureAssetId: [] | [Uint8Array];
    gstin: string;
    address: string;
    iecCode: string;
    accountNumber: string;
    branchName: string;
    phone: string;
    profileComplete: boolean;
    udyamNumber: string;
}): {
    pan: string;
    ifscCode: string;
    createdAt: bigint;
    businessName: string;
    logoAssetId?: Uint8Array;
    email: string;
    bankName: string;
    signatoryDesignation: string;
    authorizedSignatory: string;
    updatedAt: bigint;
    signatureAssetId?: Uint8Array;
    gstin: string;
    address: string;
    iecCode: string;
    accountNumber: string;
    branchName: string;
    phone: string;
    profileComplete: boolean;
    udyamNumber: string;
} {
    return {
        pan: value.pan,
        ifscCode: value.ifscCode,
        createdAt: value.createdAt,
        businessName: value.businessName,
        logoAssetId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.logoAssetId)),
        email: value.email,
        bankName: value.bankName,
        signatoryDesignation: value.signatoryDesignation,
        authorizedSignatory: value.authorizedSignatory,
        updatedAt: value.updatedAt,
        signatureAssetId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.signatureAssetId)),
        gstin: value.gstin,
        address: value.address,
        iecCode: value.iecCode,
        accountNumber: value.accountNumber,
        branchName: value.branchName,
        phone: value.phone,
        profileComplete: value.profileComplete,
        udyamNumber: value.udyamNumber
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryText: string;
    templateId: string;
    userId: Principal;
    createdAt: bigint;
    fieldValues: string;
    templateName: string;
    category: _Category;
}): {
    id: string;
    categoryText: string;
    templateId: string;
    userId: Principal;
    createdAt: bigint;
    fieldValues: string;
    templateName: string;
    category: Category;
} {
    return {
        id: value.id,
        categoryText: value.categoryText,
        templateId: value.templateId,
        userId: value.userId,
        createdAt: value.createdAt,
        fieldValues: value.fieldValues,
        templateName: value.templateName,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trade: null;
} | {
    agreement: null;
} | {
    export: null;
}): Category {
    return "trade" in value ? Category.trade : "agreement" in value ? Category.agreement : "export" in value ? Category.export : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentTemplate>): Array<DocumentTemplate> {
    return value.map((x)=>from_candid_DocumentTemplate_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentRecord>): Array<DocumentRecord> {
    return value.map((x)=>from_candid_DocumentRecord_n29(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): _BusinessProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentRecord): _DocumentRecord {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentTemplate_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentTemplate): _DocumentTemplate {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryText: string;
    templateId: string;
    userId: Principal;
    createdAt: bigint;
    fieldValues: string;
    templateName: string;
    category: Category;
}): {
    id: string;
    categoryText: string;
    templateId: string;
    userId: Principal;
    createdAt: bigint;
    fieldValues: string;
    templateName: string;
    category: _Category;
} {
    return {
        id: value.id,
        categoryText: value.categoryText,
        templateId: value.templateId,
        userId: value.userId,
        createdAt: value.createdAt,
        fieldValues: value.fieldValues,
        templateName: value.templateName,
        category: to_candid_Category_n12(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    fields: string;
    updatedAt: bigint;
    category: Category;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    fields: string;
    updatedAt: bigint;
    category: _Category;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        fields: value.fields,
        updatedAt: value.updatedAt,
        category: to_candid_Category_n12(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan: string;
    ifscCode: string;
    createdAt: bigint;
    businessName: string;
    logoAssetId?: Uint8Array;
    email: string;
    bankName: string;
    signatoryDesignation: string;
    authorizedSignatory: string;
    updatedAt: bigint;
    signatureAssetId?: Uint8Array;
    gstin: string;
    address: string;
    iecCode: string;
    accountNumber: string;
    branchName: string;
    phone: string;
    profileComplete: boolean;
    udyamNumber: string;
}): {
    pan: string;
    ifscCode: string;
    createdAt: bigint;
    businessName: string;
    logoAssetId: [] | [Uint8Array];
    email: string;
    bankName: string;
    signatoryDesignation: string;
    authorizedSignatory: string;
    updatedAt: bigint;
    signatureAssetId: [] | [Uint8Array];
    gstin: string;
    address: string;
    iecCode: string;
    accountNumber: string;
    branchName: string;
    phone: string;
    profileComplete: boolean;
    udyamNumber: string;
} {
    return {
        pan: value.pan,
        ifscCode: value.ifscCode,
        createdAt: value.createdAt,
        businessName: value.businessName,
        logoAssetId: value.logoAssetId ? candid_some(value.logoAssetId) : candid_none(),
        email: value.email,
        bankName: value.bankName,
        signatoryDesignation: value.signatoryDesignation,
        authorizedSignatory: value.authorizedSignatory,
        updatedAt: value.updatedAt,
        signatureAssetId: value.signatureAssetId ? candid_some(value.signatureAssetId) : candid_none(),
        gstin: value.gstin,
        address: value.address,
        iecCode: value.iecCode,
        accountNumber: value.accountNumber,
        branchName: value.branchName,
        phone: value.phone,
        profileComplete: value.profileComplete,
        udyamNumber: value.udyamNumber
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    trade: null;
} | {
    agreement: null;
} | {
    export: null;
} {
    return value == Category.trade ? {
        trade: null
    } : value == Category.agreement ? {
        agreement: null
    } : value == Category.export ? {
        export_: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
